### ISSUE TITLE
Investigate further Harbor deployment possibilities to ensure HA of the Harbor 

### ISSUE THREAD

**Issue by matofeder** [SovereignCloudStack/k8s-harbor#23]
This repository contains the Harbor deployment manifest that uses [helm chart for Harbor](https://github.com/goharbor/harbor-helm.git). It is coupled in the kustomize base and intended to be deployed by flux2. 

[Helm chart for Harbor](https://github.com/goharbor/harbor-helm.git) is configured here to deploy dependent databases Postgres and Redis in non-HA setup (databases are configured to be deployed with 1 replica) and uses local filesystem storage for images and charts.

Note: [Helm chart for Harbor](https://github.com/goharbor/harbor-helm.git) does not support [HA deployment for storage layer](https://github.com/goharbor/harbor-helm/blob/master/docs/High%20Availability.md). It is expected that the user provides an HA storage layer on its own. 

Investigate other possibilities for how to deploy Harbor in HA mode.

**Comment by berendt** [comment]
I think in perspective it would be good to decouple the services from the infrastructure services. Then we can also standardise the deployment of the infrastructure and, in the long term, switch to aaS. So we can take the Zalando operator directly for the DB deployment, for example, and really focus the Helm Chart for Harbor only on Harbor and consume the Zalando operator.

**Comment by matofeder** [comment]
> I think in perspective it would be good to decouple the services from the infrastructure services. Then we can also standardise the deployment of the infrastructure and, in the long term, switch to aaS. So we can take the Zalando operator directly for the DB deployment, for example, and really focus the Helm Chart for Harbor only on Harbor and consume the Zalando operator.

Agree, So let's focus on the Harbor only here (I will adjust the issue description accordingly).
 

Overall there are two ways (in Harbor [repositories](https://github.com/orgs/goharbor/repositories)) how to deploy Harbor in Kubernetes cluster (as we [discussed](https://input.osb-alliance.de/p/2023-scs-team-container) that the target infrastructure is SCS k8s cluster on top of SCS IaaS):
- [Helm chart for Harbor](https://github.com/goharbor/harbor-helm.git)
  - Harbor in HA mode
- [Harbor Operator](https://github.com/goharbor/harbor-operator) 
  - Harbor in HA mode
  - [bunch of features](https://github.com/goharbor/harbor-operator#features)
 
So let's have a look at the Harbor Operator project and whether is worth to use it and could potentially replace the Helm chart deployment used in this repository

**Comment by chess-knight** [comment]
> So let's have a look at the Harbor Operator project and whether is worth to use it and could potentially replace the Helm chart deployment used in this repository

Ok, I started to play with harbor-operator. I successfully deployed [Full stack](https://github.com/goharbor/harbor-operator#features) Harbor deployment in the local KinD *v1.24* cluster.
I also created an [upstream issue](https://github.com/goharbor/harbor-operator/issues/1017).

**Comment by chess-knight** [comment]
PR for HA Harbor is ready, see #24

**Comment by jschoone** [comment]
Hi @chess-knight, is this done by the work this week?

**Comment by chess-knight** [comment]
> Hi @chess-knight, is this done by the work this week?

Hi @jschoone. Yes, this was partially done by [#251](https://github.com/SovereignCloudStack/standards/pull/251) and now it will be closed by #24.
