### ISSUE TITLE
Deploy SCS container registry in dnation.cloud domain 

### ISSUE THREAD

**Issue by matofeder** [SovereignCloudStack/k8s-harbor#30]
As a CSP, I want to see the productive deployments of SCS container registry to ensure that SCS container registry is production ready and used by many. 

Currently, SCS reference deployment is deployed in scs.community domain and available at registry.scs.community
Deploy SCS container registry in dnation.cloud domain and make an instance publicly available.

**Comment by chess-knight** [comment]
I deployed https://registry.dnation.cloud/, config is similar to the [envs/public](https://github.com/SovereignCloudStack/k8s-harbor/tree/main/envs/public) - registry.scs.community
