### ISSUE TITLE
Harbor grafana dashboard

### ISSUE THREAD

**Issue by chess-knight** [SovereignCloudStack/k8s-harbor#39]
As a container registry administrator, I want to see exposed metrics(enabled in #29) in the Grafana dashboard.

This issue is implemented in https://github.com/dNationCloud/kubernetes-monitoring/issues/164.

**Comment by matofeder** [comment]
Closed as an upstream issue  https://github.com/dNationCloud/kubernetes-monitoring/issues/164 has been addressed.
