### ISSUE TITLE
Upgrade Kubernetes cluster that hosts SCS container registry 

### ISSUE THREAD

**Issue by matofeder** [SovereignCloudStack/k8s-harbor#54]
As a container registry operator, I want to initiate an upgrade to the latest R5 version of the SCS KaaS Kubernetes cluster that hosts the SCS Harbor container registry. This upgrade should ensure that the SCS Harbor container registry operates on top of the R5 SCS KaaS Kubernetes cluster, incorporating new features and, importantly, security fixes.

**Comment by chess-knight** [comment]
Kubernetes cluster that hosts SCS container registry has been successfully upgraded to the R5
